define(
  { "default.language" : "en",
    "use.stemming" : "false",
    "webhelp.enable.search.autocomplete" : "true",
    "webhelp.enable.search.kuromoji.js" : "true",
    "webhelp.enable.sticky.header" : "yes",
    "webhelp.enable.sticky.publication.toc" : "yes",
    "webhelp.enable.sticky.topic.toc" : "yes",
    "webhelp.enable.template.js.module.loading" : "no",
    "webhelp.language" : "en",
    "webhelp.publication.toc.links" : "all",
    "webhelp.publication.toc.tooltip.position" : "right",
    "webhelp.search.enable.pagination" : "true",
    "webhelp.search.page.numberOfItems" : "10",
    "webhelp.search.ranking" : "true",
    "webhelp.show.child.links" : "yes",
    "webhelp.show.expand.collapse.sections" : "no",
    "webhelp.show.full.size.image" : "true",
    "webhelp.show.indexterms.link" : "no",
    "webhelp.show.main.page.tiles" : "yes",
    "webhelp.show.main.page.toc" : "no",
    "webhelp.show.print.link" : "yes",
    "webhelp.show.top.menu" : "yes",
    "webhelp.sitemap.change.frequency" : "weekly",
    "webhelp.sitemap.priority" : "",
    "webhelp.top.menu.depth" : "1",
    "webhelp.topic.collapsible.elements.initial.state" : "expanded" });